name: lint-code
on: [push, pull_request]
jobs:
    mypy-linter:
        name: run mypy linter
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: "3.12"
            architecture: x64
        - name: Install bashi
          run: |
            pip install .
        - name: Install mypy
          run: |
            pip install mypy
        - name: Run mypy
          run: |
            mypy bashi

    pylint-linter:
        name: run pylint linter
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: "3.12"
            architecture: x64
        - name: Install bashi
          run: |
            pip install .
        - name: Install pylint
          run: |
            pip install pylint
        - name: Run pylint
          run: |
            pylint bashi
