name: test-and-deploy
on: [push, pull_request]
jobs:
    unit-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.10', '3.11', '3.12']
        name: Run unit tests with Python ${{ matrix.python-version }}
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: ${{ matrix.python-version }}
                architecture: x64
            - name: Install bashi
              run: |
                pip install .
            - name: run unit tests
              run: python -m unittest discover -s tests
    integration-tests:
      needs: unit-tests
      runs-on: ubuntu-latest
      name: Run example/example.py as integration test
      steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: 3.12
                architecture: x64
            - name: Install bashi
              run: |
                pip install .
            - name: run integration test
              run: python example/example.py
